#requires -Version 5.1
<#
.SYNOPSIS
  Sync portable Priority catalog skills into repo-root .grok/skills for Grok CWD discovery.

.DESCRIPTION
  Source of truth: v2/apps/mcp-catalog/catalog/<id>/SKILL.md
  Destination:     .grok/skills/<id>/SKILL.md

  Default set = Priority Agent skills (programming, formprep, shells, OData, UAT kernel,
  hours entry patterns, Bob Fleet hours webhook skills, MCP leaflets). Excludes CE Day Works product, CE DBA/backup,
  and named-person handoff skills.

  Use -IncludeDba to also sync backup/health DBA leaflets.
  Use -IncludeCustomer to also sync priority-day-works-uat (still CE-flavoured).

.EXAMPLE
  powershell -NoProfile -ExecutionPolicy Bypass -File tools\Sync-PriorityGrokSkills.ps1
#>
[CmdletBinding()]
param(
    [switch]$IncludeDba,
    [switch]$IncludeCustomer,
    [switch]$WhatIf,
    [switch]$Quiet
)
$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
$CatalogRoot = Join-Path $RepoRoot 'v2\apps\mcp-catalog\catalog'
$DestRoot = Join-Path $RepoRoot '.grok\skills'

# Customer / estate packs - not part of the default Priority Agent
$ExcludeCustomer = @(
    'priority-day-works-uat'
)
$ExcludeDba = @(
    'priority-backup-audit',
    'priority-backup-cutover',
    'priority-backup-standard',
    'priority-disk-mount-layout-report',
    'priority-instance-health-collect',
    'priority-post-move-health',
    'priority-sunday-backup-check',
    'priority-hours-handoff-haitch'
)
# Always keep harvest foundation skills (authored under .grok/skills, not catalog)
$PreserveAlways = @(
    'harvest-agent-skills',
    'harvest-priority-skills',
    'hours-log-work-session',
    'hours-classify',
    'hours-describe',
    'hours-evidence',
    'hours-correct',
    'hours-repo-metadata',
    'hours-draft'
)

if (-not (Test-Path -LiteralPath $CatalogRoot)) {
    throw "Catalog missing: $CatalogRoot"
}
New-Item -ItemType Directory -Force -Path $DestRoot | Out-Null

$exclude = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
if (-not $IncludeCustomer) { foreach ($x in $ExcludeCustomer) { [void]$exclude.Add($x) } }
if (-not $IncludeDba) { foreach ($x in $ExcludeDba) { [void]$exclude.Add($x) } }

$synced = [System.Collections.Generic.List[string]]::new()
$skipped = [System.Collections.Generic.List[string]]::new()
$missingSkill = [System.Collections.Generic.List[string]]::new()

Get-ChildItem -LiteralPath $CatalogRoot -Directory | ForEach-Object {
    $id = $_.Name
    $skillSrc = Join-Path $_.FullName 'SKILL.md'
    $metaSrc = Join-Path $_.FullName 'meta.json'
    if (-not (Test-Path -LiteralPath $metaSrc)) { return }
    if (-not (Test-Path -LiteralPath $skillSrc)) {
        [void]$missingSkill.Add($id)
        return
    }
    # Default: priority-* plus prepare-all-unprepared-*
    $isPriority = $id.StartsWith('priority-', [StringComparison]::OrdinalIgnoreCase) -or
                  $id.StartsWith('prepare-all-', [StringComparison]::OrdinalIgnoreCase)
    if (-not $isPriority) { return }
    if ($exclude.Contains($id)) {
        [void]$skipped.Add($id)
        return
    }

    $destDir = Join-Path $DestRoot $id
    $destSkill = Join-Path $destDir 'SKILL.md'
    if ($WhatIf) {
        if (-not $Quiet) { Write-Host "WHATIF sync $id" }
        [void]$synced.Add($id)
        return
    }
    New-Item -ItemType Directory -Force -Path $destDir | Out-Null
    Copy-Item -LiteralPath $skillSrc -Destination $destSkill -Force
    # Optional meta for humans / tools (Grok only needs SKILL.md)
    Copy-Item -LiteralPath $metaSrc -Destination (Join-Path $destDir 'meta.json') -Force
    [void]$synced.Add($id)
}

# Write manifest of what the Priority Agent ships
$manifestPath = Join-Path $DestRoot 'PRIORITY-AGENT-SKILLS.md'
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# Priority Agent skills (synced)')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('Generated by `tools/Sync-PriorityGrokSkills.ps1`. Do not hand-edit the list;')
[void]$sb.AppendLine('re-run the sync after catalog harvests.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine(('Generated: {0}' -f (Get-Date).ToString('yyyy-MM-dd HH:mm:ss zzz')))
[void]$sb.AppendLine(('IncludeDba={0} IncludeCustomer={1}' -f $IncludeDba, $IncludeCustomer))
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Synced')
[void]$sb.AppendLine('')
foreach ($s in ($synced | Sort-Object)) { [void]$sb.AppendLine("- $s") }
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Skipped (not default Priority Agent)')
[void]$sb.AppendLine('')
if ($skipped.Count -eq 0) { [void]$sb.AppendLine('_none_') }
else { foreach ($s in ($skipped | Sort-Object)) { [void]$sb.AppendLine("- $s") } }
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Always preserved under `.grok/skills` (not from catalog)')
[void]$sb.AppendLine('')
foreach ($s in $PreserveAlways) { [void]$sb.AppendLine("- $s") }

if (-not $WhatIf) {
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($manifestPath, $sb.ToString(), $utf8NoBom)
}

$result = [pscustomobject]@{
    ok = ($missingSkill.Count -eq 0)
    synced = @($synced | Sort-Object)
    skipped = @($skipped | Sort-Object)
    missingSkillMd = @($missingSkill | Sort-Object)
    dest = $DestRoot
    count = $synced.Count
}
if (-not $Quiet) {
    Write-Host ("Synced {0} skills -> {1}" -f $result.count, $DestRoot)
    if ($skipped.Count) { Write-Host ("Skipped {0}: {1}" -f $skipped.Count, ($skipped -join ', ')) }
    if ($missingSkill.Count) { Write-Host ("WARN missing SKILL.md: {0}" -f ($missingSkill -join ', ')) }
}
$result | ConvertTo-Json -Compress
if (-not $result.ok) { exit 1 }
exit 0
